name: "Setup Bun & Turbo"
description: "Sets up Bun, restores node_modules and Turbo cache"

inputs:
  bun-version:
    description: "Version of Bun to use"
    default: "1.3.6"

outputs:
  cache-hit:
    description: "Whether node_modules was restored from cache"
    value: ${{ steps.cache-deps.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    # Cache node_modules
    - name: Cache node_modules
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}

    # Cache Turbo artifacts
    - name: Restore Turbo Cache
      uses: actions/cache@v4
      with:
        path: .turbo
        key: turbo-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ runner.os }}-
